services:

  app:

    build:
      context: .
    container_name: sre-practice-app
    ports:
      - "5050:5050"

    environment:
      DB_HOST: postgres
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_PORT: 5432

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:

      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"
        ]

      interval: 30s
      timeout: 5s
      retries: 3


  postgres:

    image: postgres:16

    container_name: sre-postgres

    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]

      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: