name: DockerBuild

on:
  workflow_dispatch:
    


jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.12"


      - name: Install dependencies

        run: |

          pip install -r sre/app/requirements.txt


      - name: Test application

        run: |

          python -m compileall app/


  docker:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Build Docker image

        run: |

          docker build -t sre-practice-app .